os: osx

language: node_js

node_js:
  - "node"

before_install:
  - brew update
  - brew cask install sketch || ([ -z "$(brew cask outdated sketch)"] && brew cask install sketch)
  - brew cask list
  - mdfind kMDItemCFBundleIdentifier == 'com.bohemiancoding.sketch3'
  - ls /Applications

cache:
  directories:
    - "node_modules"
    - $HOME/Library/Caches/Homebrew
