os: osx

language: node_js

node_js:
  - "node"

before_install:
  - brew update
  - brew cask outdated sketch || brew cask upgrade sketch
  - npm i

cache:
  directories:
    - "node_modules"
    - $HOME/Library/Caches/Homebrew
